// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXChzKZ0lMgzlrJXR1eOlY7ydVECue62g',
    appId: '1:225431760087:web:70644a7377f2fa0636d492',
    messagingSenderId: '225431760087',
    projectId: 'apps-1bac3',
    authDomain: 'apps-1bac3.firebaseapp.com',
    databaseURL: 'https://apps-1bac3-default-rtdb.firebaseio.com',
    storageBucket: 'apps-1bac3.appspot.com',
    measurementId: 'G-669PYGY142',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4RSJSKrObBH_oS53gmYUQ9xiBjzu1UDw',
    appId: '1:225431760087:android:3c070138deccd88936d492',
    messagingSenderId: '225431760087',
    projectId: 'apps-1bac3',
    databaseURL: 'https://apps-1bac3-default-rtdb.firebaseio.com',
    storageBucket: 'apps-1bac3.appspot.com',
  );
}
